GET http://localhost:3030/admin/flats-details

### add flat
POST http://localhost:3030/admin/flat
Content-Type: application/json

{
  "block":"A",
  "flat_number":103
}

### update flat details
PUT http://localhost:3030/admin/flat/block/A/flat_number/104
Content-Type: application/json

{
  "block":"A",
  "flat_number":103
}

### delete flat 
DELETE http://localhost:3030/admin/flat/block/A/flat_number/103