GET http://localhost:3030/admin/flats-details
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyMywidXNlcl9pZCI6MTAwMSwidXNlcm5hbWUiOiJhZG1pbi5kdW1teUBnY21zLmNvbSIsInN0YXR1cyI6dHJ1ZSwicm9sZSI6ImFkbWluIn0sImlhdCI6MTY4NjU4ODg4MywiZXhwIjoxNjg3MTkzNjgzfQ.8WkC1MrjK1fc5LN3Nj9u9iIxpo3AEpGlD5Gg5khwcEs 

### get vacant flats
GET http://localhost:3030/admin/vacant-flats
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyMywidXNlcl9pZCI6MTAwMSwidXNlcm5hbWUiOiJhZG1pbi5kdW1teUBnY21zLmNvbSIsInN0YXR1cyI6dHJ1ZSwicm9sZSI6ImFkbWluIn0sImlhdCI6MTY4NjU4ODg4MywiZXhwIjoxNjg3MTkzNjgzfQ.8WkC1MrjK1fc5LN3Nj9u9iIxpo3AEpGlD5Gg5khwcEs

### add flat
POST http://localhost:3030/admin/flat
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyMywidXNlcl9pZCI6MTAwMSwidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoiJDJhJDA1JEV6bjZ6LnNiTkVEZVZTTDh5WERKUC5MMmZoWDZIbkFraGJmS0xSUldXVFJGdlU2Y1JHZFI2Iiwic3RhdHVzIjp0cnVlLCJyb2xlIjoiYWRtaW4ifSwiaWF0IjoxNjg2MjAwMDc0LCJleHAiOjE2ODY4MDQ4NzR9.43Hkt1kcirpe52v14fe-TlFvsfDlrvxlbx1QJ7y__6w 

{
  "block":"C",
  "flat_number":101
}

### update flat details
PUT http://localhost:3030/admin/flat/block/A/flat_number/104
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyMywidXNlcl9pZCI6MTAwMSwidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoiJDJhJDA1JEV6bjZ6LnNiTkVEZVZTTDh5WERKUC5MMmZoWDZIbkFraGJmS0xSUldXVFJGdlU2Y1JHZFI2Iiwic3RhdHVzIjp0cnVlLCJyb2xlIjoiYWRtaW4ifSwiaWF0IjoxNjg2MjAwMDc0LCJleHAiOjE2ODY4MDQ4NzR9.43Hkt1kcirpe52v14fe-TlFvsfDlrvxlbx1QJ7y__6w 

{
  "block":"A",
  "flat_number":103
}


###get owner details
GET http://localhost:3030/admin/owner/owner_id/20
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyMywidXNlcl9pZCI6MTAwMSwidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoiJDJhJDA1JEV6bjZ6LnNiTkVEZVZTTDh5WERKUC5MMmZoWDZIbkFraGJmS0xSUldXVFJGdlU2Y1JHZFI2Iiwic3RhdHVzIjp0cnVlLCJyb2xlIjoiYWRtaW4ifSwiaWF0IjoxNjg2MjAwMDc0LCJleHAiOjE2ODY4MDQ4NzR9.43Hkt1kcirpe52v14fe-TlFvsfDlrvxlbx1QJ7y__6w 

###
GET http://localhost:3030/admin/owners
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyMywidXNlcl9pZCI6MTAwMSwidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoiJDJhJDA1JEV6bjZ6LnNiTkVEZVZTTDh5WERKUC5MMmZoWDZIbkFraGJmS0xSUldXVFJGdlU2Y1JHZFI2Iiwic3RhdHVzIjp0cnVlLCJyb2xlIjoiYWRtaW4ifSwiaWF0IjoxNjg2MjAwMDc0LCJleHAiOjE2ODY4MDQ4NzR9.43Hkt1kcirpe52v14fe-TlFvsfDlrvxlbx1QJ7y__6w 

### add owner
POST http://localhost:3030/admin/owner
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyMywidXNlcl9pZCI6MTAwMSwidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoiJDJhJDA1JEV6bjZ6LnNiTkVEZVZTTDh5WERKUC5MMmZoWDZIbkFraGJmS0xSUldXVFJGdlU2Y1JHZFI2Iiwic3RhdHVzIjp0cnVlLCJyb2xlIjoiYWRtaW4ifSwiaWF0IjoxNjg2MjAwMDc0LCJleHAiOjE2ODY4MDQ4NzR9.43Hkt1kcirpe52v14fe-TlFvsfDlrvxlbx1QJ7y__6w 

{
  "name":"testing",
  "email":"testing@gmail.com",
  "phone":1122334455,
  "Flats":[
    {
      "block":"A",
      "flat_number":101
    }
    
  ]
}

### update owner
PUT http://localhost:3030/admin/owner/owner_id/13
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyMywidXNlcl9pZCI6MTAwMSwidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoiJDJhJDA1JEV6bjZ6LnNiTkVEZVZTTDh5WERKUC5MMmZoWDZIbkFraGJmS0xSUldXVFJGdlU2Y1JHZFI2Iiwic3RhdHVzIjp0cnVlLCJyb2xlIjoiYWRtaW4ifSwiaWF0IjoxNjg2MjAwMDc0LCJleHAiOjE2ODY4MDQ4NzR9.43Hkt1kcirpe52v14fe-TlFvsfDlrvxlbx1QJ7y__6w 

{
  "name":"vishnu",
  "email":"vishnu@gmail.com"
}


### change owner 
PUT http://localhost:3030/admin/changeOwner
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyMywidXNlcl9pZCI6MTAwMSwidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoiJDJhJDA1JEV6bjZ6LnNiTkVEZVZTTDh5WERKUC5MMmZoWDZIbkFraGJmS0xSUldXVFJGdlU2Y1JHZFI2Iiwic3RhdHVzIjp0cnVlLCJyb2xlIjoiYWRtaW4ifSwiaWF0IjoxNjg2MjAwMDc0LCJleHAiOjE2ODY4MDQ4NzR9.43Hkt1kcirpe52v14fe-TlFvsfDlrvxlbx1QJ7y__6w 

{
  "owner_id":18,
  "block":"A",
  "flat_number":103
}

### add occupant
POST http://localhost:3030/admin/occupant
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyMywidXNlcl9pZCI6MTAwMSwidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoiJDJhJDA1JEV6bjZ6LnNiTkVEZVZTTDh5WERKUC5MMmZoWDZIbkFraGJmS0xSUldXVFJGdlU2Y1JHZFI2Iiwic3RhdHVzIjp0cnVlLCJyb2xlIjoiYWRtaW4ifSwiaWF0IjoxNjg2MjAwMDc0LCJleHAiOjE2ODY4MDQ4NzR9.43Hkt1kcirpe52v14fe-TlFvsfDlrvxlbx1QJ7y__6w

{
  "occupant_name":"occupant 102",
  "email":"occupant102.dummy@abc.com",
  "phone":1122334499,
  "flat":{
    "block":"A",
    "flat_number":103,
    "ownership":"tenant"
  }
}

### get occupant details
GET http://localhost:3030/admin/occupant/6
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyMywidXNlcl9pZCI6MTAwMSwidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoiJDJhJDA1JEV6bjZ6LnNiTkVEZVZTTDh5WERKUC5MMmZoWDZIbkFraGJmS0xSUldXVFJGdlU2Y1JHZFI2Iiwic3RhdHVzIjp0cnVlLCJyb2xlIjoiYWRtaW4ifSwiaWF0IjoxNjg2MjAwMDc0LCJleHAiOjE2ODY4MDQ4NzR9.43Hkt1kcirpe52v14fe-TlFvsfDlrvxlbx1QJ7y__6w 

### get all occupants
GET http://localhost:3030/admin/occupants
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyMywidXNlcl9pZCI6MTAwMSwidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoiJDJhJDA1JEV6bjZ6LnNiTkVEZVZTTDh5WERKUC5MMmZoWDZIbkFraGJmS0xSUldXVFJGdlU2Y1JHZFI2Iiwic3RhdHVzIjp0cnVlLCJyb2xlIjoiYWRtaW4ifSwiaWF0IjoxNjg2MjAwMDc0LCJleHAiOjE2ODY4MDQ4NzR9.43Hkt1kcirpe52v14fe-TlFvsfDlrvxlbx1QJ7y__6w

### get overall occupants
GET http://localhost:3030/admin/overall-occupants 
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyMywidXNlcl9pZCI6MTAwMSwidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoiJDJhJDA1JEV6bjZ6LnNiTkVEZVZTTDh5WERKUC5MMmZoWDZIbkFraGJmS0xSUldXVFJGdlU2Y1JHZFI2Iiwic3RhdHVzIjp0cnVlLCJyb2xlIjoiYWRtaW4ifSwiaWF0IjoxNjg2MjAwMDc0LCJleHAiOjE2ODY4MDQ4NzR9.43Hkt1kcirpe52v14fe-TlFvsfDlrvxlbx1QJ7y__6w

### update occupant
PUT http://localhost:3030/admin/occupant/6
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyMywidXNlcl9pZCI6MTAwMSwidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoiJDJhJDA1JEV6bjZ6LnNiTkVEZVZTTDh5WERKUC5MMmZoWDZIbkFraGJmS0xSUldXVFJGdlU2Y1JHZFI2Iiwic3RhdHVzIjp0cnVlLCJyb2xlIjoiYWRtaW4ifSwiaWF0IjoxNjg2MjAwMDc0LCJleHAiOjE2ODY4MDQ4NzR9.43Hkt1kcirpe52v14fe-TlFvsfDlrvxlbx1QJ7y__6w 

{
  "phone":998877665
}

### delete occupant
DELETE http://localhost:3030/admin/occupant/50
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyMywidXNlcl9pZCI6MTAwMSwidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoiJDJhJDA1JEV6bjZ6LnNiTkVEZVZTTDh5WERKUC5MMmZoWDZIbkFraGJmS0xSUldXVFJGdlU2Y1JHZFI2Iiwic3RhdHVzIjp0cnVlLCJyb2xlIjoiYWRtaW4ifSwiaWF0IjoxNjg2MjAwMDc0LCJleHAiOjE2ODY4MDQ4NzR9.43Hkt1kcirpe52v14fe-TlFvsfDlrvxlbx1QJ7y__6w 

### add security guard
POST http://localhost:3030/admin/security
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyMywidXNlcl9pZCI6MTAwMSwidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoiJDJhJDA1JEV6bjZ6LnNiTkVEZVZTTDh5WERKUC5MMmZoWDZIbkFraGJmS0xSUldXVFJGdlU2Y1JHZFI2Iiwic3RhdHVzIjp0cnVlLCJyb2xlIjoiYWRtaW4ifSwiaWF0IjoxNjg2MjAwMDc0LCJleHAiOjE2ODY4MDQ4NzR9.43Hkt1kcirpe52v14fe-TlFvsfDlrvxlbx1QJ7y__6w 

{
  "name":"security101",
  "email":"security101.dummy@gmail.com",
  "phone":11223344
}

### get security details
GET http://localhost:3030/admin/security/1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyMywidXNlcl9pZCI6MTAwMSwidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoiJDJhJDA1JEV6bjZ6LnNiTkVEZVZTTDh5WERKUC5MMmZoWDZIbkFraGJmS0xSUldXVFJGdlU2Y1JHZFI2Iiwic3RhdHVzIjp0cnVlLCJyb2xlIjoiYWRtaW4ifSwiaWF0IjoxNjg2MjAwMDc0LCJleHAiOjE2ODY4MDQ4NzR9.43Hkt1kcirpe52v14fe-TlFvsfDlrvxlbx1QJ7y__6w 

###
GET http://localhost:3030/admin/all-security
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyMywidXNlcl9pZCI6MTAwMSwidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoiJDJhJDA1JEV6bjZ6LnNiTkVEZVZTTDh5WERKUC5MMmZoWDZIbkFraGJmS0xSUldXVFJGdlU2Y1JHZFI2Iiwic3RhdHVzIjp0cnVlLCJyb2xlIjoiYWRtaW4ifSwiaWF0IjoxNjg2MjAwMDc0LCJleHAiOjE2ODY4MDQ4NzR9.43Hkt1kcirpe52v14fe-TlFvsfDlrvxlbx1QJ7y__6w

### update security
PUT http://localhost:3030/admin/security/1 
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyMywidXNlcl9pZCI6MTAwMSwidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoiJDJhJDA1JEV6bjZ6LnNiTkVEZVZTTDh5WERKUC5MMmZoWDZIbkFraGJmS0xSUldXVFJGdlU2Y1JHZFI2Iiwic3RhdHVzIjp0cnVlLCJyb2xlIjoiYWRtaW4ifSwiaWF0IjoxNjg2MjAwMDc0LCJleHAiOjE2ODY4MDQ4NzR9.43Hkt1kcirpe52v14fe-TlFvsfDlrvxlbx1QJ7y__6w 

{
  "phone":9212132211
}

### delete security
DELETE http://localhost:3030/admin/security/9
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyMywidXNlcl9pZCI6MTAwMSwidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoiJDJhJDA1JEV6bjZ6LnNiTkVEZVZTTDh5WERKUC5MMmZoWDZIbkFraGJmS0xSUldXVFJGdlU2Y1JHZFI2Iiwic3RhdHVzIjp0cnVlLCJyb2xlIjoiYWRtaW4ifSwiaWF0IjoxNjg2MjAwMDc0LCJleHAiOjE2ODY4MDQ4NzR9.43Hkt1kcirpe52v14fe-TlFvsfDlrvxlbx1QJ7y__6w 

### login
POST http://localhost:3030/login
Content-Type: application/json

{
  "username":"occupant101.dummy@abc.com",
  "password":"occupant"
}

### get using sercices of occupant
GET http://localhost:3030/occupant/using-services
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyNywidXNlcl9pZCI6NDksInVzZXJuYW1lIjoib2NjdXBhbnQxMDEuZHVtbXlAYWJjLmNvbSIsInN0YXR1cyI6dHJ1ZSwicm9sZSI6Im9jY3VwYW50In0sImlhdCI6MTY4NjU5MDE1MCwiZXhwIjoxNjg3MTk0OTUwfQ.KS3objrLVwfuyvPPkKQxjgVd1AwKF0Dd8AW8qEjQIEg

### get not using sercices of occupant
GET http://localhost:3030/occupant/not-using-services
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyNywidXNlcl9pZCI6NDksInVzZXJuYW1lIjoib2NjdXBhbnQxMDEuZHVtbXlAYWJjLmNvbSIsInN0YXR1cyI6dHJ1ZSwicm9sZSI6Im9jY3VwYW50In0sImlhdCI6MTY4NjU5MDE1MCwiZXhwIjoxNjg3MTk0OTUwfQ.KS3objrLVwfuyvPPkKQxjgVd1AwKF0Dd8AW8qEjQIEg




### add services
POST http://localhost:3030/occupant/add-services
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyNywidXNlcl9pZCI6NDksInVzZXJuYW1lIjoib2NjdXBhbnQxMDEuZHVtbXlAYWJjLmNvbSIsInN0YXR1cyI6dHJ1ZSwicm9sZSI6Im9jY3VwYW50In0sImlhdCI6MTY4NjU5MDE1MCwiZXhwIjoxNjg3MTk0OTUwfQ.KS3objrLVwfuyvPPkKQxjgVd1AwKF0Dd8AW8qEjQIEg
Content-Type: application/json

{
  "services":["gym"]
}

### stop services
PUT  http://localhost:3030/occupant/stop-service
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyNywidXNlcl9pZCI6NDksInVzZXJuYW1lIjoib2NjdXBhbnQxMDEuZHVtbXlAYWJjLmNvbSIsInN0YXR1cyI6dHJ1ZSwicm9sZSI6Im9jY3VwYW50In0sImlhdCI6MTY4NjU5MDE1MCwiZXhwIjoxNjg3MTk0OTUwfQ.KS3objrLVwfuyvPPkKQxjgVd1AwKF0Dd8AW8qEjQIEg
Content-Type: application/json

{
  "service":"swimming_pool"
}

### update profile occupant
PUT http://localhost:3030/occupant/profile
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyNywidXNlcl9pZCI6NDksInVzZXJuYW1lIjoib2NjdXBhbnQxMDEuZHVtbXlAYWJjLmNvbSIsInN0YXR1cyI6dHJ1ZSwicm9sZSI6Im9jY3VwYW50In0sImlhdCI6MTY4NjU5MDE1MCwiZXhwIjoxNjg3MTk0OTUwfQ.KS3objrLVwfuyvPPkKQxjgVd1AwKF0Dd8AW8qEjQIEg

{
  "phone":9988776655
}

### get profile occupant
GET http://localhost:3030/occupant/profile
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyNywidXNlcl9pZCI6NDksInVzZXJuYW1lIjoib2NjdXBhbnQxMDEuZHVtbXlAYWJjLmNvbSIsInN0YXR1cyI6dHJ1ZSwicm9sZSI6Im9jY3VwYW50In0sImlhdCI6MTY4NjU5MDE1MCwiZXhwIjoxNjg3MTk0OTUwfQ.KS3objrLVwfuyvPPkKQxjgVd1AwKF0Dd8AW8qEjQIEg


### get bill
GET  http://localhost:3030/occupant/bill/year/2023/month/5
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyNywidXNlcl9pZCI6NDksInVzZXJuYW1lIjoib2NjdXBhbnQxMDEuZHVtbXlAYWJjLmNvbSIsInN0YXR1cyI6dHJ1ZSwicm9sZSI6Im9jY3VwYW50In0sImlhdCI6MTY4NjU5MDE1MCwiZXhwIjoxNjg3MTk0OTUwfQ.KS3objrLVwfuyvPPkKQxjgVd1AwKF0Dd8AW8qEjQIEg

### get bill -admin user
GET  http://localhost:3030/admin/bill/occupant/50/year/2023/month/5
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyMywidXNlcl9pZCI6MTAwMSwidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoiJDJhJDA1JEV6bjZ6LnNiTkVEZVZTTDh5WERKUC5MMmZoWDZIbkFraGJmS0xSUldXVFJGdlU2Y1JHZFI2Iiwic3RhdHVzIjp0cnVlLCJyb2xlIjoiYWRtaW4ifSwiaWF0IjoxNjg2MjAwMDc0LCJleHAiOjE2ODY4MDQ4NzR9.43Hkt1kcirpe52v14fe-TlFvsfDlrvxlbx1QJ7y__6w

###
GET http://localhost:3030/security/flat-details
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyMSwidXNlcl9pZCI6MywidXNlcm5hbWUiOiJzZWN1cml0eS5kdW1teUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYSQwNSRkVzdZV251ZkFYSzdDNTh1a3FONWhlSlVaL2F2Mm5pQ04vQk1sUlguY2NDRHRtMFhMSm5NMiIsInN0YXR1cyI6dHJ1ZSwicm9sZSI6InNlY3VyaXR5In0sImlhdCI6MTY4NjI5MDI3NiwiZXhwIjoxNjg2ODk1MDc2fQ.Pa3izAP1yTNrFJWx42jbojmkMko4qm_ny-Rm_ONFk_A

### add visitor record
POST http://localhost:3030/security/visitor-record
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyMSwidXNlcl9pZCI6MywidXNlcm5hbWUiOiJzZWN1cml0eS5kdW1teUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYSQwNSRkVzdZV251ZkFYSzdDNTh1a3FONWhlSlVaL2F2Mm5pQ04vQk1sUlguY2NDRHRtMFhMSm5NMiIsInN0YXR1cyI6dHJ1ZSwicm9sZSI6InNlY3VyaXR5In0sImlhdCI6MTY4NjI5MDI3NiwiZXhwIjoxNjg2ODk1MDc2fQ.Pa3izAP1yTNrFJWx42jbojmkMko4qm_ny-Rm_ONFk_A
Content-Type: application/json

{
  "visitor_name":"visitor",
  "visitor_aadhar":99887766554433,
  "purpose":"relatives",
  "phone":9632587410
}

### get not vacated visitors record
GET http://localhost:3030/security/not-vacated-visitors-record
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyMywidXNlcl9pZCI6MTAwMSwidXNlcm5hbWUiOiJhZG1pbi5kdW1teUBnY21zLmNvbSIsInN0YXR1cyI6dHJ1ZSwicm9sZSI6ImFkbWluIn0sImlhdCI6MTY4NjU4ODg4MywiZXhwIjoxNjg3MTkzNjgzfQ.8WkC1MrjK1fc5LN3Nj9u9iIxpo3AEpGlD5Gg5khwcEs

### note return time
PUT http://localhost:3030/security/return/visitor_id/2
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyMywidXNlcl9pZCI6MTAwMSwidXNlcm5hbWUiOiJhZG1pbi5kdW1teUBnY21zLmNvbSIsInN0YXR1cyI6dHJ1ZSwicm9sZSI6ImFkbWluIn0sImlhdCI6MTY4NjU4ODg4MywiZXhwIjoxNjg3MTkzNjgzfQ.8WkC1MrjK1fc5LN3Nj9u9iIxpo3AEpGlD5Gg5khwcEs

### update visitor record
PUT http://localhost:3030/security/update-visitor-record/visitor_id/1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyMywidXNlcl9pZCI6MTAwMSwidXNlcm5hbWUiOiJhZG1pbi5kdW1teUBnY21zLmNvbSIsInN0YXR1cyI6dHJ1ZSwicm9sZSI6ImFkbWluIn0sImlhdCI6MTY4NjU4ODg4MywiZXhwIjoxNjg3MTkzNjgzfQ.8WkC1MrjK1fc5LN3Nj9u9iIxpo3AEpGlD5Gg5khwcEs

{
  "visitor_name":"updated"
}

### get all visitors record
GET http://localhost:3030/security/visitors-record
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyMSwidXNlcl9pZCI6MywidXNlcm5hbWUiOiJzZWN1cml0eS5kdW1teUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYSQwNSRkVzdZV251ZkFYSzdDNTh1a3FONWhlSlVaL2F2Mm5pQ04vQk1sUlguY2NDRHRtMFhMSm5NMiIsInN0YXR1cyI6dHJ1ZSwicm9sZSI6InNlY3VyaXR5In0sImlhdCI6MTY4NjI5MDI3NiwiZXhwIjoxNjg2ODk1MDc2fQ.Pa3izAP1yTNrFJWx42jbojmkMko4qm_ny-Rm_ONFk_A

### get visitors record on particular time
POST http://localhost:3030/security/visitors-record-on-time
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyMywidXNlcl9pZCI6MTAwMSwidXNlcm5hbWUiOiJhZG1pbi5kdW1teUBnY21zLmNvbSIsInN0YXR1cyI6dHJ1ZSwicm9sZSI6ImFkbWluIn0sImlhdCI6MTY4NjU4ODg4MywiZXhwIjoxNjg3MTkzNjgzfQ.8WkC1MrjK1fc5LN3Nj9u9iIxpo3AEpGlD5Gg5khwcEs
Content-Type: application/json

{
  "start_time":"Fri Jun 09 2023 09:36:02 GMT+0530",
  "end_time":"Fri Jun 09 2023 13:37:02 GMT+0530"
}

### change password
POST http://localhost:3030/change-password
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJfaWQiOjEwMDEsInVzZXJuYW1lIjoiYWRtaW4uZHVtbXlAZ2Ntcy5jb20iLCJzdGF0dXMiOnRydWUsInJvbGUiOiJhZG1pbiJ9LCJpYXQiOjE2ODY1NTM5OTgsImV4cCI6MTY4NzE1ODc5OH0.S-5LwwESVNxvY2CEYZ4YwU3s1sJec-Z-PkNzb8UrtKs

{
  "old_password":"admin@123",
  "new_password":"admin@123"
}

### forgot password link
POST http://localhost:3030/forgot-password
Content-Type: application/json

{
  "username":"occupant101.dummy@abc.com	"
}

### reset password 
POST http://localhost:3030/reset-password
Content-Type: application/json

{
  "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im9jY3VwYW50MTAxLmR1bW15QGFiYy5jb20iLCJpYXQiOjE2ODY1NjUyNzIsImV4cCI6MTY4NjU2NTg3Mn0.VcA1QiDyg6q91dN5DvzMyEdX1CPeWrHCJhHypg--JRk",
  "password":"occupant@123"
}

### 
PUT http://localhost:3030/admin/update-service-costs
Content-Type: application/json

{
  "gym":1000
}

###send mail to all occupants
POSt http://localhost:3030/admin/mail-to-occupants
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyMywidXNlcl9pZCI6MTAwMSwidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoiJDJhJDA1JEV6bjZ6LnNiTkVEZVZTTDh5WERKUC5MMmZoWDZIbkFraGJmS0xSUldXVFJGdlU2Y1JHZFI2Iiwic3RhdHVzIjp0cnVlLCJyb2xlIjoiYWRtaW4ifSwiaWF0IjoxNjg2MjAwMDc0LCJleHAiOjE2ODY4MDQ4NzR9.43Hkt1kcirpe52v14fe-TlFvsfDlrvxlbx1QJ7y__6w 
Content-Type: application/json

{
  "subject":"testing bulk emails|Gated Community Management System",
  "text":"Hey , Good evening.. This is test email for all occupants"
}