GET http://localhost:3030/admin/flats-details
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyMywidXNlcl9pZCI6MTAwMSwidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoiJDJhJDA1JEV6bjZ6LnNiTkVEZVZTTDh5WERKUC5MMmZoWDZIbkFraGJmS0xSUldXVFJGdlU2Y1JHZFI2Iiwic3RhdHVzIjp0cnVlLCJyb2xlIjoiYWRtaW4ifSwiaWF0IjoxNjg2MjAwMDc0LCJleHAiOjE2ODY4MDQ4NzR9.43Hkt1kcirpe52v14fe-TlFvsfDlrvxlbx1QJ7y__6w 

### get vacant flats
GET http://localhost:3030/admin/vacant-flats
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyMywidXNlcl9pZCI6MTAwMSwidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoiJDJhJDA1JEV6bjZ6LnNiTkVEZVZTTDh5WERKUC5MMmZoWDZIbkFraGJmS0xSUldXVFJGdlU2Y1JHZFI2Iiwic3RhdHVzIjp0cnVlLCJyb2xlIjoiYWRtaW4ifSwiaWF0IjoxNjg2MjAwMDc0LCJleHAiOjE2ODY4MDQ4NzR9.43Hkt1kcirpe52v14fe-TlFvsfDlrvxlbx1QJ7y__6w

### add flat
POST http://localhost:3030/admin/flat
Content-Type: application/json

{
  "block":"B",
  "flat_number":102
}

### update flat details
PUT http://localhost:3030/admin/flat/block/A/flat_number/104
Content-Type: application/json

{
  "block":"A",
  "flat_number":103
}

### delete flat 
DELETE http://localhost:3030/admin/flat/block/A/flat_number/103

###get owner details
GET http://localhost:3030/admin/owner/owner_id/2

### add owner
POST http://localhost:3030/admin/owner
Content-Type: application/json

{
  "name":"testing",
  "email":"testing@gmail.com",
  "phone":1122334455,
  "Flats":[
    {
      "block":"A",
      "flat_number":103
    },
    {
      "block":"B",
      "flat_number":101
    },
    {
      "block":"B",
      "flat_number":102
    }
  ]
}

### update owner
PUT http://localhost:3030/admin/owner/owner_id/13
Content-Type: application/json

{
  "name":"vishnu",
  "email":"vishnu@gmail.com"
}

### delete owner
DELETE http://localhost:3030/admin/owner/owner_id/2

### change owner 
PUT http://localhost:3030/admin/changeOwner
Content-Type: application/json

{
  "owner_id":13,
  "block":"A",
  "flat_number":103
}

### add occupant
POST http://localhost:3030/admin/occupant
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyMywidXNlcl9pZCI6MTAwMSwidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoiJDJhJDA1JEV6bjZ6LnNiTkVEZVZTTDh5WERKUC5MMmZoWDZIbkFraGJmS0xSUldXVFJGdlU2Y1JHZFI2Iiwic3RhdHVzIjp0cnVlLCJyb2xlIjoiYWRtaW4ifSwiaWF0IjoxNjg2MjAwMDc0LCJleHAiOjE2ODY4MDQ4NzR9.43Hkt1kcirpe52v14fe-TlFvsfDlrvxlbx1QJ7y__6w

{
  "occupant_name":"occupant 102",
  "email":"occupant102.dummy@abc.com",
  "phone":1122334499,
  "flat":{
    "block":"A",
    "flat_number":101,
    "ownership":"tenant"
  }
}

### get occupant details
GET http://localhost:3030/admin/occupant/6

### update occupant
PUT http://localhost:3030/admin/occupant/6
Content-Type: application/json

{
  "phone":9988776655
}

### delete occupant
DELETE http://localhost:3030/admin/occupant/48
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyMywidXNlcl9pZCI6MTAwMSwidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoiJDJhJDA1JEV6bjZ6LnNiTkVEZVZTTDh5WERKUC5MMmZoWDZIbkFraGJmS0xSUldXVFJGdlU2Y1JHZFI2Iiwic3RhdHVzIjp0cnVlLCJyb2xlIjoiYWRtaW4ifSwiaWF0IjoxNjg2MjAwMDc0LCJleHAiOjE2ODY4MDQ4NzR9.43Hkt1kcirpe52v14fe-TlFvsfDlrvxlbx1QJ7y__6w 

### add security guard
POST http://localhost:3030/admin/security
Content-Type: application/json

{
  "name":"security1",
  "email":"security.dummy@gmail.com",
  "phone":11223344
}

### get security details
GET http://localhost:3030/admin/security/1

### update security
PUT http://localhost:3030/admin/security/1 
Content-Type: application/json

{
  "name":"security updated"
}

### delete security
DELETE http://localhost:3030/admin/security/3

### login
POST http://localhost:3030/login
Content-Type: application/json

{
  "username":"admin.dummy@gcms.com",
  "password":"admin@12"
}

### get using sercices of occupant
GET http://localhost:3030/occupant/using-services
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyNCwidXNlcl9pZCI6NDYsInVzZXJuYW1lIjoib2NjdXBhbnQuZHVtbXlAYWJjLmNvbSIsInBhc3N3b3JkIjoiJDJhJDA1JDY3c2RvNDdxWURlbzkzTUZvL3RTUnVxc0V5eEdGM2ZTLlVZN1pRdXhPR3F1MkM3WHFaMU1HIiwic3RhdHVzIjp0cnVlLCJyb2xlIjoib2NjdXBhbnQifSwiaWF0IjoxNjg2MjA1Njc4LCJleHAiOjE2ODY4MTA0Nzh9.mf9qM9yLlOv6u5-FnAh7XxiYS7iZuoWVG1G2N29uFm0

### get not using sercices of occupant
GET http://localhost:3030/occupant/not-using-services
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyNCwidXNlcl9pZCI6NDYsInVzZXJuYW1lIjoib2NjdXBhbnQuZHVtbXlAYWJjLmNvbSIsInBhc3N3b3JkIjoiJDJhJDA1JDY3c2RvNDdxWURlbzkzTUZvL3RTUnVxc0V5eEdGM2ZTLlVZN1pRdXhPR3F1MkM3WHFaMU1HIiwic3RhdHVzIjp0cnVlLCJyb2xlIjoib2NjdXBhbnQifSwiaWF0IjoxNjg2MjA1Njc4LCJleHAiOjE2ODY4MTA0Nzh9.mf9qM9yLlOv6u5-FnAh7XxiYS7iZuoWVG1G2N29uFm0




### add services
POST http://localhost:3030/occupant/add-services
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyOCwidXNlcl9pZCI6NTAsInVzZXJuYW1lIjoib2NjdXBhbnQxMDIuZHVtbXlAYWJjLmNvbSIsInBhc3N3b3JkIjoiJDJhJDA1JGxWUU1YVElFQlFZVW5zTUNtUWRLNS5TeDRUS0E4YlMvYVVFY2VDandDS1FENDRUbjBIZEs2Iiwic3RhdHVzIjp0cnVlLCJyb2xlIjoib2NjdXBhbnQifSwiaWF0IjoxNjg2MjI3NTY2LCJleHAiOjE2ODY4MzIzNjZ9.dxvjwY_oEbJPG7ec3i-_Bfyoc1w_1mAFo91dB6kK7aY
Content-Type: application/json

{
  "services":["swimming_pool","gym"]
}

### stop services
DELETE  http://localhost:3030/occupant/stop-service
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyOCwidXNlcl9pZCI6NTAsInVzZXJuYW1lIjoib2NjdXBhbnQxMDIuZHVtbXlAYWJjLmNvbSIsInBhc3N3b3JkIjoiJDJhJDA1JGxWUU1YVElFQlFZVW5zTUNtUWRLNS5TeDRUS0E4YlMvYVVFY2VDandDS1FENDRUbjBIZEs2Iiwic3RhdHVzIjp0cnVlLCJyb2xlIjoib2NjdXBhbnQifSwiaWF0IjoxNjg2MjI3NTY2LCJleHAiOjE2ODY4MzIzNjZ9.dxvjwY_oEbJPG7ec3i-_Bfyoc1w_1mAFo91dB6kK7aY
Content-Type: application/json

{
  "service":"swimming_pool"
}

### update profile occupant
PUT http://localhost:3030/occupant/profile
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyNywidXNlcl9pZCI6NDksInVzZXJuYW1lIjoib2NjdXBhbnQxMDEuZHVtbXlAYWJjLmNvbSIsInBhc3N3b3JkIjoiJDJhJDA1JGplMGlTclBJMDRWL05aYTQ1UDdhQXVlbWoxWTR3TC84Li5ZckM4YjVoY2cuNGkwMnl0ZXpXIiwic3RhdHVzIjp0cnVlLCJyb2xlIjoib2NjdXBhbnQifSwiaWF0IjoxNjg2Mjg2MTc5LCJleHAiOjE2ODY4OTA5Nzl9.Zyfyvc3tH_D_eBQ9mO-6MWL5-WrUtph_OBzF-MjJccw

{
  "phone":9988776655
}

### get profile occupant
GET http://localhost:3030/occupant/profile
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyNywidXNlcl9pZCI6NDksInVzZXJuYW1lIjoib2NjdXBhbnQxMDEuZHVtbXlAYWJjLmNvbSIsInBhc3N3b3JkIjoiJDJhJDA1JGplMGlTclBJMDRWL05aYTQ1UDdhQXVlbWoxWTR3TC84Li5ZckM4YjVoY2cuNGkwMnl0ZXpXIiwic3RhdHVzIjp0cnVlLCJyb2xlIjoib2NjdXBhbnQifSwiaWF0IjoxNjg2Mjg2MTc5LCJleHAiOjE2ODY4OTA5Nzl9.Zyfyvc3tH_D_eBQ9mO-6MWL5-WrUtph_OBzF-MjJccw


### get bill
GET  http://localhost:3030/occupant/bill/year/2023/month/5
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyNywidXNlcl9pZCI6NDksInVzZXJuYW1lIjoib2NjdXBhbnQxMDEuZHVtbXlAYWJjLmNvbSIsInBhc3N3b3JkIjoiJDJhJDA1JGplMGlTclBJMDRWL05aYTQ1UDdhQXVlbWoxWTR3TC84Li5ZckM4YjVoY2cuNGkwMnl0ZXpXIiwic3RhdHVzIjp0cnVlLCJyb2xlIjoib2NjdXBhbnQifSwiaWF0IjoxNjg2Mjg2MTc5LCJleHAiOjE2ODY4OTA5Nzl9.Zyfyvc3tH_D_eBQ9mO-6MWL5-WrUtph_OBzF-MjJccw

### get bill -admin user
GET  http://localhost:3030/admin/bill/occupant/40/year/2023/month/5
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyMywidXNlcl9pZCI6MTAwMSwidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoiJDJhJDA1JEV6bjZ6LnNiTkVEZVZTTDh5WERKUC5MMmZoWDZIbkFraGJmS0xSUldXVFJGdlU2Y1JHZFI2Iiwic3RhdHVzIjp0cnVlLCJyb2xlIjoiYWRtaW4ifSwiaWF0IjoxNjg2MjAwMDc0LCJleHAiOjE2ODY4MDQ4NzR9.43Hkt1kcirpe52v14fe-TlFvsfDlrvxlbx1QJ7y__6w

###
GET http://localhost:3030/security/flat-details
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyMSwidXNlcl9pZCI6MywidXNlcm5hbWUiOiJzZWN1cml0eS5kdW1teUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYSQwNSRkVzdZV251ZkFYSzdDNTh1a3FONWhlSlVaL2F2Mm5pQ04vQk1sUlguY2NDRHRtMFhMSm5NMiIsInN0YXR1cyI6dHJ1ZSwicm9sZSI6InNlY3VyaXR5In0sImlhdCI6MTY4NjI5MDI3NiwiZXhwIjoxNjg2ODk1MDc2fQ.Pa3izAP1yTNrFJWx42jbojmkMko4qm_ny-Rm_ONFk_A

### add visitor record
POST http://localhost:3030/security/visitor-record
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyMSwidXNlcl9pZCI6MywidXNlcm5hbWUiOiJzZWN1cml0eS5kdW1teUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYSQwNSRkVzdZV251ZkFYSzdDNTh1a3FONWhlSlVaL2F2Mm5pQ04vQk1sUlguY2NDRHRtMFhMSm5NMiIsInN0YXR1cyI6dHJ1ZSwicm9sZSI6InNlY3VyaXR5In0sImlhdCI6MTY4NjI5MDI3NiwiZXhwIjoxNjg2ODk1MDc2fQ.Pa3izAP1yTNrFJWx42jbojmkMko4qm_ny-Rm_ONFk_A
Content-Type: application/json

{
  "visitor_name":"visitor",
  "visitor_aadhar":99887766554433,
  "visiting_to":49,
  "purpose":"relatives"
}

### get not vacated visitors record
GET http://localhost:3030/security/not-vacated-visitors-record
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyMSwidXNlcl9pZCI6MywidXNlcm5hbWUiOiJzZWN1cml0eS5kdW1teUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYSQwNSRkVzdZV251ZkFYSzdDNTh1a3FONWhlSlVaL2F2Mm5pQ04vQk1sUlguY2NDRHRtMFhMSm5NMiIsInN0YXR1cyI6dHJ1ZSwicm9sZSI6InNlY3VyaXR5In0sImlhdCI6MTY4NjI5MDI3NiwiZXhwIjoxNjg2ODk1MDc2fQ.Pa3izAP1yTNrFJWx42jbojmkMko4qm_ny-Rm_ONFk_A

### nore return time
PUT http://localhost:3030/security/return/visitor_id/1
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyMSwidXNlcl9pZCI6MywidXNlcm5hbWUiOiJzZWN1cml0eS5kdW1teUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYSQwNSRkVzdZV251ZkFYSzdDNTh1a3FONWhlSlVaL2F2Mm5pQ04vQk1sUlguY2NDRHRtMFhMSm5NMiIsInN0YXR1cyI6dHJ1ZSwicm9sZSI6InNlY3VyaXR5In0sImlhdCI6MTY4NjI5MDI3NiwiZXhwIjoxNjg2ODk1MDc2fQ.Pa3izAP1yTNrFJWx42jbojmkMko4qm_ny-Rm_ONFk_A

### update visitor record
PUT http://localhost:3030/security/update-visitor-record/visitor_id/1
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyMSwidXNlcl9pZCI6MywidXNlcm5hbWUiOiJzZWN1cml0eS5kdW1teUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYSQwNSRkVzdZV251ZkFYSzdDNTh1a3FONWhlSlVaL2F2Mm5pQ04vQk1sUlguY2NDRHRtMFhMSm5NMiIsInN0YXR1cyI6dHJ1ZSwicm9sZSI6InNlY3VyaXR5In0sImlhdCI6MTY4NjI5MDI3NiwiZXhwIjoxNjg2ODk1MDc2fQ.Pa3izAP1yTNrFJWx42jbojmkMko4qm_ny-Rm_ONFk_A
Content-Type: application/json

{
  "visitor_name":"updated"
}

### get all visitors record
GET http://localhost:3030/security/visitors-record
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyMSwidXNlcl9pZCI6MywidXNlcm5hbWUiOiJzZWN1cml0eS5kdW1teUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYSQwNSRkVzdZV251ZkFYSzdDNTh1a3FONWhlSlVaL2F2Mm5pQ04vQk1sUlguY2NDRHRtMFhMSm5NMiIsInN0YXR1cyI6dHJ1ZSwicm9sZSI6InNlY3VyaXR5In0sImlhdCI6MTY4NjI5MDI3NiwiZXhwIjoxNjg2ODk1MDc2fQ.Pa3izAP1yTNrFJWx42jbojmkMko4qm_ny-Rm_ONFk_A

### get visitors record on particular time
POST http://localhost:3030/security/visitors-record-on-time
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyMywidXNlcl9pZCI6MTAwMSwidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoiJDJhJDA1JEV6bjZ6LnNiTkVEZVZTTDh5WERKUC5MMmZoWDZIbkFraGJmS0xSUldXVFJGdlU2Y1JHZFI2Iiwic3RhdHVzIjp0cnVlLCJyb2xlIjoiYWRtaW4ifSwiaWF0IjoxNjg2MjAwMDc0LCJleHAiOjE2ODY4MDQ4NzR9.43Hkt1kcirpe52v14fe-TlFvsfDlrvxlbx1QJ7y__6w
Content-Type: application/json

{
  "start_time":"Fri Jun 09 2023 09:36:02 GMT+0530",
  "end_time":"Fri Jun 09 2023 13:37:02 GMT+0530"
}

### change password
POST http://localhost:3030/change-password
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyMywidXNlcl9pZCI6MTAwMSwidXNlcm5hbWUiOiJhZG1pbi5kdW1teUBnY21zLmNvbSIsInBhc3N3b3JkIjoiJDJhJDA1JFdlOFQuZWFwa2l6VG1GeFdUT0VSdmV0YkZKWmlkTjlXUmR0SDgzTkdVRGdPMzJkR0ZwaE4uIiwic3RhdHVzIjp0cnVlLCJyb2xlIjoiYWRtaW4iLCJyZXNldF90b2tlbiI6ImV5SmhiR2NpT2lKSVV6STFOaUlzSW5SNWNDSTZJa3BYVkNKOS5leUoxYzJWeWJtRnRaU0k2SW1Ga2JXbHVMbVIxYlcxNVFHZGpiWE11WTI5dElpd2lhV0YwSWpveE5qZzJNekE0TVRRMkxDSmxlSEFpT2pFMk9EWXpNRGczTkRaOS5weE80MTR1UjB0NFY1c0ZYRGZLTFRUUFpSRFJleWI4MHBaN3FmcjZEN1lVIn0sImlhdCI6MTY4NjMwODIxMCwiZXhwIjoxNjg2OTEzMDEwfQ.NQBl3BeLdqMNM65F5BfEjfDKT6sdACkQ1xoBVL3LF-Q
Content-Type: application/json

{
  "old_password":"admin@12",
  "new_password":"admin@123"
}

### forgot password link
POST http://localhost:3030/forgot-password
Content-Type: application/json

{
  "username":"admin.dummy@gcms.com"
}

### reset password 
POST http://localhost:3030/reset-password
Content-Type: application/json

{
  "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluLmR1bW15QGdjbXMuY29tIiwiaWF0IjoxNjg2MzA3OTMzLCJleHAiOjE2ODYzMDg1MzN9.y3u_ey5p9TLH_EeQD3gmS15ziPGxUIQaMOk1yFZapwY",
  "password":"admin@12"
}

### 
PUT http://localhost:3030/admin/update-service-costs
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyMywidXNlcl9pZCI6MTAwMSwidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoiJDJhJDA1JEV6bjZ6LnNiTkVEZVZTTDh5WERKUC5MMmZoWDZIbkFraGJmS0xSUldXVFJGdlU2Y1JHZFI2Iiwic3RhdHVzIjp0cnVlLCJyb2xlIjoiYWRtaW4ifSwiaWF0IjoxNjg2MjAwMDc0LCJleHAiOjE2ODY4MDQ4NzR9.43Hkt1kcirpe52v14fe-TlFvsfDlrvxlbx1QJ7y__6w 
Content-Type: application/json

{
  "swimming_pool":1000
}
